kernel,initramfs: Add checks for missing files in hook scripts
Attempting to handle the case where the package has been removed but not
purged.

diff --git a/initramfs/z-cluster-netboot b/initramfs/z-cluster-netboot
--- a/initramfs/z-cluster-netboot
+++ b/initramfs/z-cluster-netboot
@@ -5,4 +5,10 @@ if [ -n "$INITRAMFS_TOOLS_KERNEL_HOOK" ]; then
 	exit 0
 fi
 
-DEB_MAINT_PARAMS=configure /etc/kernel/postinst.d/z-cluster-netboot $1
+KERNEL_HOOK=/etc/kernel/postinst.d/z-cluster-netboot
+if [ -x "$KERNEL_HOOK" ]; then
+	DEB_MAINT_PARAMS=configure $KERNEL_HOOK $1
+else
+	echo "Unable to execute ${KERNEL_HOOK}"
+	exit 1
+fi
